2023-05-30 16:33:42,773 INFO    MainThread:1861611 [wandb_setup.py:_flush():68] Configure stats pid to 1861611
2023-05-30 16:33:42,773 INFO    MainThread:1861611 [wandb_setup.py:_flush():68] Loading settings from /home/wenxuan/.config/wandb/settings
2023-05-30 16:33:42,773 INFO    MainThread:1861611 [wandb_setup.py:_flush():68] Loading settings from /home/wenxuan/Partial_Distance_Correlation/TF_Diverge_Training/wandb/settings
2023-05-30 16:33:42,773 INFO    MainThread:1861611 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True', 'api_key': '***REDACTED***'}
2023-05-30 16:33:42,773 INFO    MainThread:1861611 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'TF_Diverge_Training/training.py', 'program': 'training.py'}
2023-05-30 16:33:42,773 INFO    MainThread:1861611 [wandb_init.py:_log_setup():476] Logging user logs to /home/wenxuan/Partial_Distance_Correlation/TF_Diverge_Training/wandb/run-20230530_163342-1zov1sd4/logs/debug.log
2023-05-30 16:33:42,774 INFO    MainThread:1861611 [wandb_init.py:_log_setup():477] Logging internal logs to /home/wenxuan/Partial_Distance_Correlation/TF_Diverge_Training/wandb/run-20230530_163342-1zov1sd4/logs/debug-internal.log
2023-05-30 16:33:42,774 INFO    MainThread:1861611 [wandb_init.py:init():516] calling init triggers
2023-05-30 16:33:42,774 INFO    MainThread:1861611 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2023-05-30 16:33:42,774 INFO    MainThread:1861611 [wandb_init.py:init():569] starting backend
2023-05-30 16:33:42,774 INFO    MainThread:1861611 [wandb_init.py:init():573] setting up manager
2023-05-30 16:33:42,785 ERROR   MainThread:1861611 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/home/wenxuan/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/wenxuan/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 574, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/wenxuan/.local/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 173, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/wenxuan/.local/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py", line 35, in _svc_inform_init
    _pbmap_apply_dict(inform_init._settings_map, settings_dict)
  File "/home/wenxuan/.local/lib/python3.8/site-packages/wandb/sdk/service/service_base.py", line 41, in _pbmap_apply_dict
    sv.tuple_value.string_values.extend(v)
TypeError: None has type NoneType, but expected one of: bytes, unicode
